blank_issues_enabled: true
contact_links:
  - name: 申请变更 & 举报问题网站 & 申请退出
    url: https://www.travellings.cn/docs/qa#q-%E6%88%91%E9%9C%80%E8%A6%81%E5%8F%98%E6%9B%B4%E7%BD%91%E5%9D%80%E6%88%96%E4%B8%BE%E6%8A%A5%E9%97%AE%E9%A2%98%E7%BD%91%E9%A1%B5%E6%88%96%E9%80%80%E5%87%BA%E5%BC%80%E5%BE%80%E6%88%96%E8%81%94%E7%B3%BB%E7%AB%99%E9%95%BF
    about: 前往官网“疑难解答”页面查看详细说明
  - name: 其他 Issue
    url: https://github.com/travellings-link/travellings/issues/new
    about: 创建一个空白的 Issue，不使用 Issue 模板
  - name: 问题 & 讨论 & 建议
    url: https://github.com/travellings-link/travellings/discussions
    about: 使用 GitHub 讨论进行留言板式的问题和讨论或功能建议
