name: Issue Reply1

on:
  issues:
    types: [labeled]

jobs:
  reply-helper:
    runs-on: ubuntu-latest
    steps:
      - name: out vercel
        if: github.event.label.name == 'cn'
        uses: actions-cool/issues-helper@v2.0.0
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            您好，开往的地址已更换为 https://www.travellings.cn/go.html ，相关LOGO图片新地址如下：
            gif动图：https://www.travellings.cn/assets/logo.gif
            svg：https://www.travellings.cn/assets/logo.svg
            请您及时更换相关地址，谢谢配合。
