# 带有`待回应`,`审核驳回`标签的 Issue 在 15 天未活动之后会被关闭

name: Close timeout issues
on:
  schedule:
    # Runs at 16:00 UTC/24:00 CST every day.
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v7
        with:
          days-before-stale: -1
          days-before-issue-stale: 15
          days-before-issue-close: 0
          stale-issue-label: '超时'
          only-issue-labels: '待回应,审核驳回'
          close-issue-message: '距离上次等待您的回复，已经过去15天，团队将关闭您的本次请求，如您后续希望继续申请，可以重新提交 Issue 再次申请。感谢您对 开往-友链接力 的支持！'
          remove-issue-stale-when-updated: true
