# 带有`观察期`标签的 Issue 在 32 天未活动之后会被关闭

name: Close timeout issues
on:
  schedule:
    # Runs at 12:00 UTC/20:00 CST every day.
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v7
        with:
          days-before-stale: -1
          days-before-issue-stale: 32
          days-before-issue-close: 0
          stale-issue-label: "审核通过"
          only-issue-labels: "观察期"
          close-issue-message: "恭喜您通过申请，您可在[成员列表](https://api.travellings.cn/all)中搜索到您的站点。"
          remove-issue-stale-when-updated: true
          ascending: true
          operations-per-run: 50
